#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Music-Harmonics
version:      0.01
version_from: lib/Music/Harmonics.pm
installdirs:  site
requires:
    MIDI::Pitch:                   0.4
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
